version: "3.8" # Usa la versión más reciente compatible.

services:
  guarapo_lab_test:
    image: guarapo_lab_test
    ports:
      - "8080:8080"
    environment:
      ADDRESS_HTTP: ":8080"
      ADDRESS_HTTPS: ":4443"
      READ_TIMEOUT: "5"
      WRITE_TIMEOUT: "5"
      PERSISTENCE_TYPE: "inmemory"